Repository eclipse/smarthome, pull requests merged in 2018-09, with the labels that each got.

#6147 Paper UI: further control page refactoring
  extensions/ui/org.eclipse.smarthome.ui.paper/package.json
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/views.css
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/color/component.control.color.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.item.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.item.js
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.tab.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.tab.js
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/contact/component.control.contact.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/control.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/controllers.control.js
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/dimmer/component.control.dimmer.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/image/component.control.image.js
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/component.control.location.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/number/component.control.number.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/number/component.control.number.js
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/player/component.control.player.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/rollershutter/component.control.rollershutter.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/rollershutter/component.control.rollershutter.js
Labels: UI-PaperUI

#6121 WU: bridge/thing refactoring
  extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/thing/bridge.xml
  extensions/binding/org.eclipse.smarthome.binding.weatherunderground/README.md
  extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundBridgeHandler.java
  extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java
  extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/WeatherUndergroundHandlerFactory.java
  extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/config/WeatherUndergroundConfiguration.java
  extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/discovery/WeatherUndergroundDiscoveryService.java
Labels: Binding-Weather-Underground

#6163 Paper UI: fix control page style
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/views.css
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/color/component.control.color.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.item.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.tab.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/contact/component.control.contact.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/dimmer/component.control.dimmer.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/image/component.control.image.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/component.control.location.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/number/component.control.number.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/player/component.control.player.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/rollershutter/component.control.rollershutter.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/string/component.control.string.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/switch/component.control.switch.html
Labels: UI-PaperUI

#6159 Paper UI: validate location input
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/configuration/directive.configDescription.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/configuration/directive.locationParameter.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/configuration/directive.locationParameter.js
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/component.control.location.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/component.control.location.js
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/directive.validation.location.js
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/map/component.control.map.js
Labels: UI-PaperUI

#6165 WU: automatic handling of French Canadian and British English
  extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java
  extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/discovery/WeatherUndergroundDiscoveryService.java
Labels: Binding-Weather-Underground

#6182 Fixed handling of OFFLINE things in case of multiple links in AutoUpdateManager
  bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/internal/AutoUpdateManagerTest.java
  bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/AutoUpdateManager.java
Labels: Core

#6181 Paper UI: Allow multiple map widgets on the same page
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/map/component.control.map.html
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/map/component.control.map.js
Labels: UI-PaperUI

#6188 Improved lifecycle management of PersistenceManager
  bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/PersistenceManager.java
  bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/PersistenceManagerImpl.java
  distribution/smarthome/conf/items/demo.items
  distribution/smarthome/conf/persistence/mapdb.persist
  targetplatform/SmartHome-Runtime.launch
Labels: Persistence

#6271 [astro] Add german translation for moon eclipses
  extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/i18n/astro_de.properties
Labels: Binding-Astro

#6279 Paper UI: retain given options for contexts ITEM, THING, CHANNEL, RULE
  extensions/ui/org.eclipse.smarthome.ui.paper/tests/configService.test.js
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
Labels: UI-PaperUI

#6268 [homematic] Provide more functionality in the bridge handler
  extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/handler/HomematicBridgeHandler.java
  extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/AbstractHomematicGateway.java
  extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/HomematicGateway.java
  extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/client/RpcClient.java
Labels: Binding-Homematic

#6278 Align group function EQUALITY
  bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/GroupFunctionHelper.java
  bundles/model/org.eclipse.smarthome.model.item.tests/org.eclipse.smarthome.model.item.tests.launch
  bundles/model/org.eclipse.smarthome.model.item.tests/src/org/eclipse/smarthome/model/item/internal/GenericItemProviderTest.java
  bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/Items.xtext
  bundles/model/org.eclipse.smarthome.model.rule.tests/org.eclipse.smarthome.model.rule.tests.launch
  docs/documentation/concepts/items.md
Labels: APIBreaking

#6237 Deprecate & deactivate DiscoveryServiceCallback and ExtendedDiscovery…
  bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/java/org/eclipse/smarthome/config/discovery/DiscoveryServiceRegistryOSGiTest.java
  bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/java/org/eclipse/smarthome/config/setup/test/discovery/ExtendedDiscoveryServiceMock.java
  bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryServiceCallback.java
  bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/ExtendedDiscoveryService.java
  bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java
  docs/documentation/development/bindings/discovery-services.md
Labels: APIBreaking

#6286 Paper UI: set label for context parameter options when missing
  extensions/ui/org.eclipse.smarthome.ui.paper/tests/configService.test.js
  extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
Labels: UI-PaperUI
